name: Project Theta MLOps Demo

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy xgboost scikit-learn imbalanced-learn fastapi uvicorn pydantic joblib

    - name: 🚀 Step 1 - Train and Save Model Assets
      run: |
        echo "Running the training pipeline to create models/..."
        python fraud_system.py
        
    - name: Verify Model Assets Exist
      run: |
        ls -l models/
        test -f models/fraud_detection_xgb_model.joblib ||
