name: Project Theta MLOps Demo

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # ✅ FIXED: Changed 'imblearn' to 'imbalanced-learn'
        pip install pandas numpy xgboost scikit-learn imbalanced-learn fastapi uvicorn pydantic joblib

    - name: 🚀 Step 1: Train and Save Model Assets
      run: |
        echo "Running the training pipeline..."
        python fraud_system.py
        
    - name: Verify Model Assets Exist
      run: |
        echo "Checking models directory contents..."
        ls -la models/
        test -f models/fraud_detection_xgb_model.joblib || exit 1
        test -f models/scaler.joblib || exit 1
        echo "✅ Model assets confirmed."

    - name: 🧪 Step 2: Run API Smoke Test
      run: |
        echo "Starting FastAPI service in background..."
        uvicorn api_service:app --host 0.0.0.0 --port 8000 &
        
        # ✅ FIXED: Increased wait time from 5 to 10 seconds
        echo "Waiting for API startup (10 seconds)..."
        sleep 10
        
        # ✅ FIXED: Added health check before testing
        echo "Testing health endpoint..."
        curl -X GET "http://0.0.0.0:8000/health" || echo "Warning: Health check failed"
        
        echo ""
        echo "Testing GREEN (ACCEPT) transaction..."
        curl -X POST "http://0.0.0.0:8000/api/v1/predict_fraud" \
             -H "Content-Type: application/json" \
             -d '{"user_id": "test_green", "amount": 300.0, "distance_from_last_tx": 0.1, "hour_of_day": 10, "count_tx_1h": 2}'
        
        echo ""
        echo ""
        echo "Testing RED (BLOCK) transaction..."
        curl -X POST "http://0.0.0.0:8000/api/v1/predict_fraud" \
             -H "Content-Type: application/json" \
             -d '{"user_id": "test_red", "amount": 95000.0, "distance_from_last_tx": 10.0, "hour_of_day": 3, "count_tx_1h": 15}'

        echo ""
        echo "✅ API smoke test complete."

    - name: 🛑 Workflow Finished
      run: echo "🎉 Project Theta build and test workflow successfully completed!"
